version: "3.8"

services:
  app:
    build: rdp
    container_name: "RDP-client"
    restart: always
    networks:
      - rdp-network
    secrets:
      - username
      - password
      - version

    deploy:
      replicas: 1

  front-novnc:
    build: novnc
    container_name: "novnc-front"
    restart: always
    networks:
      - rdp-network
    ports:
      - 8086:80
    deploy:
      replicas: 1

networks:
  rdp-network:

secrets:
  username:
    file: ./username
  password:
    file: ./password
  version:
    file: ./version

