version: "3.8"

services:
  app:
    build: xfreerdp
    container_name: "FreeRDP2-X11"
    restart: always
    networks:
      - rdp-network
    environment:
      RDP_USERNAME_FILE: /run/secrets/username
      RDP_PASSWORD_FILE: /run/secrets/password
    secrets:
      - username
      - password
    deploy:
      replicas: 1

  front-novnc:
    build: novnc
    container_name: "novnc-front"
    restart: always
    networks:
      - rdp-network
    ports:
      - 8086:80
    deploy:
      replicas: 1

networks:
  rdp-network:

secrets:
  username:
    file: ./username
  password:
    file: ./password

